### ISSUE TITLE
Usage of special characters inside the translations (&nbsp;)

### ISSUE THREAD

**Issue by Vinnythetrue** [dkfbasel/vuex-i18n#106]
I'm using the i18n module in my app, working well, great module, thanks for the job.

But I would like to use special characters, ie. &nbsp; inside some of my texts.
For instance, in french, there is a space before an exclamation mark, I would love to put a nonbreakingspace there instead of a regular space, but putting the litteral string "&nbsp;" in the text data inside the json file makes it appear just like that in the browser instead of being interpreted by the browser.

How should I achieve that ?

**Comment by tikiatua** [comment]
Hi @Vinnythetrue,

Thank you for your feedback. This is indeed a tricky problem and has to do with character encoding and html escaping.

For security reasons, vue will automatically escape all html tags – i.e. the &nbsp; tag – in text unless you use the v-html directive to insert the content. Be aware, that using the v-html directive might open your application up to possible security vulnerabilities. Especially if it is used on content that users can specify.

However, the content can contain a range of characters, which is usually encoded in a specific format. Nowadays I would suggest to use the utf-8 encoding for most websites that use latin characters (exceptions for special languages like Arabic, Chinese, Japanese, ..).

You can specify the encoding to use for the website in a meta tag
```html
<head>
  <meta charset="UTF-8">
</head>
```

Make sure that the content in the json file is also encoded in utf-8 (i.e. in VSCode this can be set in the toolbar on left the bottom). Now you need to actually use a non-breaking space instead of a regular space in the json content. To enter a non breaking space you need to use the unicode code to insert the character, which is 00A0 (http://www.fileformat.info/info/unicode/char/00a0/index.htm).

There are different ways of inserting a special unicode character depending on your operating system:
- On windows, you hold down the ALT key and press the + key on the number keypad. Then you enter the hexadecimal unicode value (i.e. 00A0) and release the ALT key.
- On OS X, this is slightly more complicated and involves activating the unicode keyboard. Details can be found here https://poynton.ca/notes/misc/mac-unicode-hex-input.html

Please let me know if this solves your problem.

**Comment by Vinnythetrue** [comment]
thanks tikiatua ! The solution was so simple, I even didn't though of simply insert the "real" non-breaking space unicode character O_o

It works like a charm !

The only downside for me, is when it comes to the translation work, I will have to process somehow the texts coing back from translation, because the translation people won't be able to do this I guess...

Thanks again :)
