### ISSUE TITLE
vuex-persistedData()

### ISSUE THREAD

**Issue by viktorvillalobos** [dkfbasel/vuex-i18n#27]
I'm using the [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) plugin, but for some reason i18n is not stuck in the store, any ideas?

**Comment by tikiatua** [comment]
Hi @viktorvillalobos,

Thank you for your request. I did take a quick look at the vuex-persistedstate plugin, but did not yet really understand how the plugin achieves its functionality.

The problem might arise due to us using a separate vuex store module (i18n by default) to save the translation data. This might not be handled by the reducer introduced with the vuex-persistedstate plugin and thus not saved in the local storage.

However, I will have to get back to you at a later time, as I am going to be off for some days in the mountains.

**Comment by viktorvillalobos** [comment]
Hi @tikiatua , thanks for response.

> The problem might arise due to us using a separate vuex store module (i18n by default) to save the translation data.

This is the problem, anyway happy holidays.

**Comment by tikiatua** [comment]
Closing this, as the problem arises due to the way huex-persistedstate handles persistence.
