### ISSUE TITLE
Changing languages dynamically with Nuxt

### ISSUE THREAD

**Issue by aft3rlife** [dkfbasel/vuex-i18n#33]
Hi, I'm trying to use this with Nuxt as a plugin like so:

```JS
import Vue from 'vue'
import vuexI18n from 'vuex-i18n'

import store from '~/store'

import en from '~/locales/en.json'
import fr from '~/locales/fr.json'

Vue.use(vuexI18n.plugin, store())

Vue.i18n.add('en', en)
Vue.i18n.add('fr', fr)

Vue.i18n.set(store().state.locale)
```

Which works fine however when changing the language in the state (from locale = 'en to locale = 'fr' for example) the strings aren't changed on the fly. Is there any way to achieve this?

**Comment by tikiatua** [comment]
Hi @aft3rlife,

Thank you for your question. Setting the locale with Vue.i18n.set(store().state.locale) will dispatch an action to the i18n module in the store with the current value of `locale`. Updating the locale in the store will not re-dispatch the action and thus not update the translations.

However, I can think of three possible approaches that should be feasible to achieve what you intend to:

1. Instead of having a separate locale in your state you directly use the locale in the i18n module. I.e. if you change the locale or need to display it somewhere you do this directly with the i18n.set() and i18n.locale() methods provided by the vuex-i18n plugin. 
2. You could watch the locale value (https://vuejs.org/v2/api/#watch) and dispatch a new Vue.i18n.set event when the locale changes.
3. You could write a small vuex plugin (this is actually very easy, https://vuex.vuejs.org/en/plugins.html) that would react on all mutations to the locale state and dispatch a corresponding Vue.i18n.set event.

Please let me know if one of these approaches will work for you, or if you need some further help.
