### ISSUE TITLE
$t function returns ascii codes for special characters

### ISSUE THREAD

**Issue by corcus** [dkfbasel/vuex-i18n#37]
Hi,

I am using vue in combination with server side rendering (Razor views from ASP.NET MVC).
I am using the vuex-i18n plugin to get translations inside vue components (which are off-course not rendered server side).

The way I set the translations is the following
```
Vue.i18n.add('@LanguageHelper.CurrentFrontendLanguageSymbol', {
            'label_result': '@("label_result".Translate())' });
```
The LanguageHelper and Translate functions provide the necessary values on the server side rendering time. They will later be used inside some vue components like this
`{{ $t("label_result") }}`

The problem I am facing is with special characters.
For example if "label_result".Translate() gives the value "résultat" then what I get from $t("label_result") is r#233;sultat. The special characters are encoded in ascii. 

Do you know why this happens?

**Comment by tikiatua** [comment]
Hi @corcus 

This sounds like an interesting problem. I do need some clarification to help you with this. So if I understand you correctly, you basically want to specify translations with special non ascii characters and the result should be the text string but not encoded in ascii.

```
Vue.i18n.add('es', {
    'label_result': 'résultat'
});

{{ $t('label_result') }} 
// should result in: résultat
```

Doing this in the test file, that we have in this repository does return the string correctly without special character encoding. Therefore I would deduct that the reason for your problem is (a) the razor template engine is encoding the string in ascii or (b) the file format is not in utf-8 and the server or an intermediate parser does some magic to encode the string in ascii.

A quick search for a problem with automatic encoding of non ascii characters in razor points towards this issue https://github.com/aspnet/HttpAbstractions/issues/315 from which I would take the automatic encoding could be due to the XSS-protection enabled in the razor engine. Probably worth to take a closer look at this.

Please let me know if this is of any help – P.S. this is why we use golang for server side stuff. Less magic can sometimes be helpful ;-)

**Comment by corcus** [comment]
You have understood my goal correctly.

I will read into the issue you provided. It does seem interesting.
In the meantime I have found a workaround. Instead of using the mustache syntax {{}} which [interprets the data as plain text](https://vuejs.org/v2/guide/syntax.html#Raw-HTML) I use the **v-html** directive
and it looks like this 
`<div v-html='$t("label_result")'></div>`

Thanks for your response and the useful link
