### ISSUE TITLE
Unexpected token: keyword (default)

### ISSUE THREAD

**Issue by nkoehring** [dkfbasel/vuex-i18n#4]
To be able to use the module, I needed to change the main file in package.json to `dist/vuex-i18n.cjs.js`. I installed vuex-i18n as usual with `npm install vuex-i18n --save`.

If I don't do that, I get:
```
ERROR in static/js/vendor.f87486b0e9be75a67cda.js from UglifyJs
SyntaxError: Unexpected token: keyword (default) [./~/vuex-i18n/dist/vuex-i18n.es.js:461,0]
```

What's wrong?

**Comment by ktquez** [comment]
@nkoehring 
I can do it this way `vuex-i18n/dist/vuex-i18n.cjs`

**Comment by nkoehring** [comment]
Thanks, this works as expected! Shouldn't this be reasonable in a more elegant way, though?

**Comment by tikiatua** [comment]
Hi there,

The reason this is necessary, is because the main file is written in es6 and webpack can only include commonjs modules (if babel is not used previously).

In my opinion the es6 module system is the way to go for the future. Babel will automatically transpile es6 modules to commonjs and webpack 2 does support es6 modules directly. http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/

However, it seems, that the need of this pipeline is currently posing a problem and I will try to modify the package so it can be included more easily. New version should be online tomorrow.

**Comment by tikiatua** [comment]
This should be fixed now by using umd module specification for the default minified source
