### ISSUE TITLE
Adding component as parameter

### ISSUE THREAD

**Issue by AlexanderReiswich** [dkfbasel/vuex-i18n#42]
Hi there,

I'm looking for a way to include another component within a translation.
So here's a hypothetical example:

`"View my <vue-link>profile</vue-link>!"`

So basically the translation function should look like this:

`$t('view_profile', {'profile': '<vue-link>profile</vue-link>'})`

And the string:

`"View my {profile}!"`

Of course the component won't render when you simply pass it as a parameter. But how can it be done?

(Naturally the translation could be split, but that of course can result in rather awkward partial strings)

**Comment by tikiatua** [comment]
Hi @AlexanderReiswich,

I do understand your usecase, however, unfortunately this is currently not possible. 

The problem is, that the <vue-link> component needs to be transpiled into a javascript function that will in turn render the respective component. We save simple translation strings in the vuex store, therefore this would probably require a major rewrite of the plugin.

We currently split the respective strings or use components with v-if-else to support similar use cases.
