### ISSUE TITLE
this.$t("xxx") can‘t switch language,but {{$t("xxx") }} can,I don't know why！！！！！

### ISSUE THREAD

**Issue by cyf593240704** [dkfbasel/vuex-i18n#43]
God, I wrote {{$in Vue (“content”)}} can switch in English, but in JS this.cont = this.$t (”content“) to display only a word, after switching to no effect, this is what happened in the ah, no wrong, why can be written in HTML, JS assigned to data data binding is not? Call for help!!!

**Comment by cyf593240704** [comment]
Why is it written in HTML, and the assignment to data bound data in JS is no good? Call for help!

**Comment by tikiatua** [comment]
Hi @cyf593240704,

Thank you for your question. Unfortunately I cannot completely understand your problem with the information you provided. Please post some more code surrounding the issue. 

However, I would think, that your understanding of the inner "magic" of vue needs some clarification.

Vue properties in html templates - the {{$t('something'}} part - are reactive. This means that vue will sort of observe the properties and update the template automatically if the property changed. This is coupled with a virtual dom that makes this process very effective.

In javascript methods this is not automatically the case. Javascript code is only executed again for computed properties that contain properties that have change. It somewhat also work in methods, if the component is updated due to a property that has changed in the vue template. Please check if this might be the case for you.

On a side note: Please try to be as specific if possible when submitting an issue and refrain from adding things like multiple exclamation marks in the title of an issue as this makes it somewhat difficult for other people to quickly browse through issues.

**Comment by cyf593240704** [comment]
main.js
import 'babel-polyfill';  //es6
import Vue from 'vue';
import Vuex from 'vuex';
import vuexI18n from 'vuex-i18n';
import App from './App';
import router from './router';
Vue.use(Vuex);
const store = new Vuex.Store({
    /*modules: {
        i18n: vuexI18n.store
    },*/
    state: {
        lang:'zh-cn'
    },
    mutations:{
        changeLangMu(state, lang){
            // state.lang = lang;
            Vue.i18n.set(state.lang);
        }
    }
});
Vue.use(vuexI18n.plugin, store);
import translationsEn from'@/lang/en';
import translationsZh from'@/lang/zh-cn';

Vue.i18n.add('en', translationsEn);
Vue.i18n.add('zh-cn', translationsZh);
Vue.i18n.set(store.state.lang);

Vue.config.productionTip = false
/* eslint-disable no-new */
new Vue({
  store,
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})

**Comment by cyf593240704** [comment]
App.vue

<template>
  <div class="hello">
    <button @click=changeLang() >{{lang}}</button>
    <div>vue:{{$t('content')}}</div>
    <div>js:{{content}}</div>
  </div>
</template>

<script>
export default {
  name: 'hello',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
      lang:'English',
      content:'',
    }
  },

  created(){
    this.content = this.$t("content");
  },
  methods:{
      changeLang(){
        var lang = this.$store.state.lang ;
        if(lang == 'zh-cn'){
          this.$store.state.lang = 'en';
          this.lang = '中文';
        }else{
          this.$store.state.lang = 'zh-cn';
          this.lang = 'English';
        }
        this.$store.commit('changeLangMu',this.lang)
      }
  },
}
</script>


<style scoped>
h1, h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>

**Comment by cyf593240704** [comment]
export default {
  name: 'hello',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
      lang:'English',
      content:'',
    }
  },

  created(){
    this.content = this.$t("content");
  },
  methods:{
      changeLang(){
        var lang = this.$store.state.lang ;
        if(lang == 'zh-cn'){
          this.$store.state.lang = 'en';
          this.lang = '中文';
        }else{
          this.$store.state.lang = 'zh-cn';
          this.lang = 'English';
        }
        this.$store.commit('changeLangMu',this.lang)
      }
  },
}
</script>

**Comment by cyf593240704** [comment]
App.js
export default {
  name: 'hello',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App',
      lang:'English',
      content:'',
    }
  },

  created(){
    this.content = this.$t("content");
  },
  methods:{
      changeLang(){
        var lang = this.$store.state.lang ;
        if(lang == 'zh-cn'){
          this.$store.state.lang = 'en';
          this.lang = '中文';
        }else{
          this.$store.state.lang = 'zh-cn';
          this.lang = 'English';
        }
        this.$store.commit('changeLangMu',this.lang)
      }
  },
}
</script>

**Comment by cyf593240704** [comment]
<div class="hello">
    <button @click=changeLang() >{{lang}}</button>
    <div>vue:{{$t('content')}}</div>
    <div>js:{{content}}</div>
  </div>

**Comment by cyf593240704** [comment]
App.vue

<div class="hello">
    <button @click=changeLang() >{{lang}}</button>
    <div>vue:{{$t('content')}}</div>
    <div>js:{{content}}</div>
  </div>

**Comment by cyf593240704** [comment]
How can this.t (''content'') written in JS be able to switch language like $t ('content') in Vue?
