### ISSUE TITLE
Translate outside of templates

### ISSUE THREAD

**Issue by Buzut** [dkfbasel/vuex-i18n#44]
First of all, thank you for this awesome plugin! 

`$t` or filter methods seem to be available in templates ony. I'd need to pass translations dynamically via components props inside the router like so:

```js
routes: [
   {
     path: '/',
     name: 'Login',
     component: login,
     props: { title: localizedTitle }
  }
]
```

Is this possible? How should it be done?

**Comment by tikiatua** [comment]
Hi @Buzut

Thank you for your question. The problem is, that you need access to the vuex store, which is usually not available in the file where you setup your routes. 

You could manage this by having an init function for all routes to which you pass the vue instance that has the store attached. Then you can access the translations through the vue.i18n.translate function. However, it could be, that the title might not be updated in the props, if you change the localization and the component is already rendered.

``` javascript
// something like this
func init(vueInstance) {
    return [
       {
           path: '/',
           name: 'Login',
           component: login,
           props: (route) => ({ title: vueInstance.i18n.translate(title) })
       }
   ]
}
```
A simpler option might be to localize the text in the component or to encapsulate the login component in a localization component.

Please let me know if any of this works for you.

**Comment by Buzut** [comment]
Hi @tikiatua 

Thank you for your kind answer. 

Finally, I managed things a bit differently. I'm passing the translation placeholder rather than the translation itself and let the component handle the actual translation with `$t` method. This works equally well. 

As the variable is holding the translation placeholder, it mustn't be escaped in the `$t` function, that's all.

```html
<template>
<div>
  <h1>$t(title)</h1>
</div>
</template>
```

**Comment by tikiatua** [comment]
Great. Thanks for the update
